from tasks.assignment.assets.assets_assignment_ui import (
    ALL_ABOUT_BOOTHILL_CHECK, ALL_ABOUT_BOOTHILL_CLICK,
    CHARACTER_MATERIALS_CHECK, CHARACTER_MATERIALS_CLICK,
    EXP_MATERIALS_CREDITS_CHECK, EXP_MATERIALS_CREDITS_CLICK, GROUP_SEARCH,
    SYNTHESIS_MATERIALS_CHECK, SYNTHESIS_MATERIALS_CLICK)

for group_button_wrapper in (
    ALL_ABOUT_BOOTHILL_CHECK, ALL_ABOUT_BOOTHILL_CLICK,
    CHARACTER_MATERIALS_CHECK, CHARACTER_MATERIALS_CLICK,
    EXP_MATERIALS_CREDITS_CHECK, EXP_MATERIALS_CREDITS_CLICK,
    SYNTHESIS_MATERIALS_CHECK, SYNTHESIS_MATERIALS_CLICK,
):
    group_button_wrapper.load_search(GROUP_SEARCH.button)
