name: Bug Report
description: Create a report to help us improve
labels: ['bug / 缺陷']
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Before you asking
      options:
      - label: I have searched the existing issues
        required: true
      - label: I spend at least 5 minutes for thinking and preparing
        required: true
      - label: I am using the latest version of SRC
        required: true
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: Text
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        If applicable, add screenshots to help explain your problem.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    id: others
    attributes:
      label: Anything else?
      description: |
        Related configs? Links? References?
        Anything that will give us more context about the issue you are encountering!
    validations:
      required: false