from .classes import ItemCurrency

# This file was auto-generated, do not modify it manually. To generate:
# ``` python -m dev_tools.keyword_extract ```

Stellar_Jade = ItemCurrency(
    id=1,
    name='Stellar_Jade',
    cn='星琼',
    cht='星瓊',
    en='Stellar Jade',
    jp='星玉',
    es='Jade estelar',
    rarity='SuperRare',
    item_id=1,
    item_group=0,
    dungeon_id=-1,
)
Credit = ItemCurrency(
    id=2,
    name='Credit',
    cn='信用点',
    cht='信用點',
    en='Credit',
    jp='信用ポイント',
    es='Crédito',
    rarity='Rare',
    item_id=2,
    item_group=0,
    dungeon_id=-1,
)
Oneiric_Shard = ItemCurrency(
    id=3,
    name='Oneiric_Shard',
    cn='古老梦华',
    cht='古老夢華',
    en='Oneiric Shard',
    jp='往日の夢華',
    es='Esquirla onírica',
    rarity='SuperRare',
    item_id=3,
    item_group=0,
    dungeon_id=-1,
)
Trailblaze_Power = ItemCurrency(
    id=4,
    name='Trailblaze_Power',
    cn='开拓力',
    cht='開拓力',
    en='Trailblaze Power',
    jp='開拓力',
    es='Poder trazacaminos',
    rarity='VeryRare',
    item_id=11,
    item_group=0,
    dungeon_id=-1,
)
Reserved_Trailblaze_Power = ItemCurrency(
    id=5,
    name='Reserved_Trailblaze_Power',
    cn='后备开拓力',
    cht='後備開拓力',
    en='Reserved Trailblaze Power',
    jp='予備開拓力',
    es='Poder trazacaminos de reserva',
    rarity='VeryRare',
    item_id=12,
    item_group=0,
    dungeon_id=-1,
)
EXP = ItemCurrency(
    id=6,
    name='EXP',
    cn='经验',
    cht='經驗',
    en='EXP',
    jp='経験',
    es='EXP',
    rarity='Rare',
    item_id=21,
    item_group=0,
    dungeon_id=-1,
)
Trailblaze_EXP = ItemCurrency(
    id=7,
    name='Trailblaze_EXP',
    cn='里程',
    cht='里程',
    en='Trailblaze EXP',
    jp='マイレージ',
    es='EXP trazacaminos',
    rarity='Rare',
    item_id=22,
    item_group=0,
    dungeon_id=-1,
)
Activity = ItemCurrency(
    id=8,
    name='Activity',
    cn='活跃度',
    cht='活躍度',
    en='Activity',
    jp='アクティブ度',
    es='Actividad',
    rarity='Rare',
    item_id=23,
    item_group=0,
    dungeon_id=-1,
)
Trailblaze_Timer = ItemCurrency(
    id=9,
    name='Trailblaze_Timer',
    cn='开拓进行时',
    cht='開拓進行時',
    en='Trailblaze Timer',
    jp='開拓進行計',
    es='Trazascopio',
    rarity='SuperRare',
    item_id=24,
    item_group=0,
    dungeon_id=-1,
)
The_Returning_Trail = ItemCurrency(
    id=10,
    name='The_Returning_Trail',
    cn='归程轨迹',
    cht='歸程軌跡',
    en='The Returning Trail',
    jp='帰還の軌跡',
    es='Trayectoria de regreso',
    rarity='Rare',
    item_id=25,
    item_group=0,
    dungeon_id=-1,
)
Cosmic_Fragment = ItemCurrency(
    id=11,
    name='Cosmic_Fragment',
    cn='宇宙碎片',
    cht='宇宙碎片',
    en='Cosmic Fragment',
    jp='宇宙の欠片',
    es='Fragmentos cósmicos',
    rarity='Rare',
    item_id=31,
    item_group=0,
    dungeon_id=-1,
)
Ability_Point = ItemCurrency(
    id=12,
    name='Ability_Point',
    cn='技能点',
    cht='技能點',
    en='Ability Point',
    jp='アビリティポイント',
    es='Punto de habilidad',
    rarity='Rare',
    item_id=32,
    item_group=0,
    dungeon_id=-1,
)
Immersifier = ItemCurrency(
    id=13,
    name='Immersifier',
    cn='沉浸器',
    cht='沉浸器',
    en='Immersifier',
    jp='没入器',
    es='Inmersor',
    rarity='VeryRare',
    item_id=33,
    item_group=0,
    dungeon_id=-1,
)
Achievement_Points = ItemCurrency(
    id=14,
    name='Achievement_Points',
    cn='成就点数',
    cht='成就點數',
    en='Achievement Points',
    jp='アチーブメントポイント',
    es='Puntos de logro',
    rarity='Rare',
    item_id=41,
    item_group=0,
    dungeon_id=-1,
)
The_Nameless_EXP = ItemCurrency(
    id=15,
    name='The_Nameless_EXP',
    cn='无名客的经验',
    cht='無名客的經驗',
    en='The Nameless EXP',
    jp='ナナシビトの経験',
    es='EXP anónima',
    rarity='Rare',
    item_id=51,
    item_group=0,
    dungeon_id=-1,
)
The_Nameless_EXP = ItemCurrency(
    id=16,
    name='The_Nameless_EXP',
    cn='无名客的经验',
    cht='無名客的經驗',
    en='The Nameless EXP',
    jp='ナナシビトの経験',
    es='EXP anónima',
    rarity='Rare',
    item_id=52,
    item_group=0,
    dungeon_id=-1,
)
Development_Fund = ItemCurrency(
    id=17,
    name='Development_Fund',
    cn='发展资金',
    cht='發展資金',
    en='Development Fund',
    jp='発展資金',
    es='Fondos de desarrollo',
    rarity='Rare',
    item_id=53,
    item_group=0,
    dungeon_id=-1,
)
