from .classes import ItemExp

# This file was auto-generated, do not modify it manually. To generate:
# ``` python -m dev_tools.keyword_extract ```

Travel_Encounters = ItemExp(
    id=1,
    name='Travel_Encounters',
    cn='旅情见闻',
    cht='旅情見聞',
    en='Travel Encounters',
    jp='旅の見聞',
    es='Noticias del viaje',
    rarity='NotNormal',
    item_id=211,
    item_group=1010,
    dungeon_id=1001,
)
Adventure_Log = ItemExp(
    id=2,
    name='Adventure_Log',
    cn='冒险记录',
    cht='冒險紀錄',
    en='Adventure Log',
    jp='冒険記録',
    es='Registro de aventuras',
    rarity='Rare',
    item_id=212,
    item_group=1010,
    dungeon_id=1001,
)
Traveler_Guide = ItemExp(
    id=3,
    name='Traveler_Guide',
    cn='漫游指南',
    cht='漫遊指南',
    en="Traveler's Guide",
    jp='漫遊指南',
    es='Guía del espíritu viajero',
    rarity='VeryRare',
    item_id=213,
    item_group=1010,
    dungeon_id=1001,
)
Sparse_Aether = ItemExp(
    id=4,
    name='Sparse_Aether',
    cn='稀薄以太',
    cht='稀薄乙太',
    en='Sparse Aether',
    jp='希薄なエーテル',
    es='Éter disperso',
    rarity='NotNormal',
    item_id=221,
    item_group=1020,
    dungeon_id=1002,
)
Condensed_Aether = ItemExp(
    id=5,
    name='Condensed_Aether',
    cn='凝缩以太',
    cht='凝縮乙太',
    en='Condensed Aether',
    jp='濃縮エーテル',
    es='Éter condensado',
    rarity='Rare',
    item_id=222,
    item_group=1020,
    dungeon_id=1002,
)
Refined_Aether = ItemExp(
    id=6,
    name='Refined_Aether',
    cn='提纯以太',
    cht='精煉乙太',
    en='Refined Aether',
    jp='精製エーテル',
    es='Éter refinado',
    rarity='VeryRare',
    item_id=223,
    item_group=1020,
    dungeon_id=1002,
)
Lost_Lightdust = ItemExp(
    id=7,
    name='Lost_Lightdust',
    cn='遗失光尘',
    cht='遺失光塵',
    en='Lost Lightdust',
    jp='遺失光塵',
    es='Polvo luminoso perdido',
    rarity='NotNormal',
    item_id=231,
    item_group=1030,
    dungeon_id=-1,
)
Lost_Gold_Fragment = ItemExp(
    id=8,
    name='Lost_Gold_Fragment',
    cn='遗失碎金',
    cht='遺失碎金',
    en='Lost Gold Fragment',
    jp='遺失砕金',
    es='Fragmento dorado perdido',
    rarity='Rare',
    item_id=232,
    item_group=1030,
    dungeon_id=-1,
)
Lost_Crystal = ItemExp(
    id=9,
    name='Lost_Crystal',
    cn='遗失晶块',
    cht='遺失晶塊',
    en='Lost Crystal',
    jp='遺失晶塊',
    es='Cristal perdido',
    rarity='VeryRare',
    item_id=233,
    item_group=1030,
    dungeon_id=-1,
)
Lost_Essence = ItemExp(
    id=10,
    name='Lost_Essence',
    cn='遗失精粹',
    cht='遺失精粹',
    en='Lost Essence',
    jp='遺失精華',
    es='Esencia perdida',
    rarity='SuperRare',
    item_id=234,
    item_group=1030,
    dungeon_id=-1,
)
